backend:
  name: git-gateway
  branch: main

media_folder: "uploads"      # CMS 上でアップロードした画像の保存先（リポジトリ内）
public_folder: "/uploads"    # サイト上で画像にアクセスするパス

collections:
  - name: "products"
    label: "Products (single file)"
    files:
      - file: "products/products.json"
        label: "Products JSON"
        name: "products_json"
        fields:
          - { name: "items", label: "Products", widget: "list", summary: "{{fields.title}}", fields:
              - { name: "id", label: "ID", widget: "string" }
              - { name: "title", label: "Title", widget: "string" }
              - { name: "price", label: "Price", widget: "number" }
              - { name: "category", label: "Category", widget: "string" }
              - { name: "tags", label: "Tags", widget: "list" }
              - { name: "sizes", label: "Sizes", widget: "list" }
              - { name: "image", label: "Image", widget: "image" }
              - { name: "description", label: "Description", widget: "text" }
              - { name: "published", label: "Published", widget: "boolean", default: true }
            ]
